import { Document, Packer, Paragraph, Table, TableCell, TableRow, WidthType, AlignmentType, HeadingLevel, TextRun } from 'docx';

const CORS_HEADERS = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export const handler = async (event) => {
    if (event.httpMethod === 'OPTIONS') {
        return { statusCode: 200, headers: CORS_HEADERS, body: '' };
    }
    if (event.httpMethod !== 'POST') {
        return { statusCode: 405, headers: CORS_HEADERS, body: JSON.stringify({ message: 'Method not allowed' }) };
    }

    try {
        const { title, elements } = JSON.parse(event.body || '{}');
        if (!title || !elements) {
            return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ message: 'title and elements are required' }) };
        }

        const headerCell = (text, width) =>
            new TableCell({
                children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })],
                width: { size: width, type: WidthType.PERCENTAGE },
            });

        const bodyCell = (text) =>
            new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: text || '' })] })] });

        const doc = new Document({
            sections: [{
                properties: {},
                children: [
                    new Paragraph({
                        children: [new TextRun({ text: `Claim Chart: ${title}`, bold: true })],
                        heading: HeadingLevel.HEADING_1,
                        alignment: AlignmentType.CENTER,
                    }),
                    new Paragraph({ children: [] }),
                    new Table({
                        width: { size: 100, type: WidthType.PERCENTAGE },
                        rows: [
                            new TableRow({
                                children: [headerCell('ID', 10), headerCell('Claim Element', 30), headerCell('Evidence', 30), headerCell('Reasoning', 30)],
                            }),
                            ...elements.map(el => new TableRow({
                                children: [bodyCell(el.id), bodyCell(el.element), bodyCell(el.evidence), bodyCell(el.reasoning)],
                            })),
                        ],
                    }),
                    new Paragraph({ children: [] }),
                    new Paragraph({
                        children: [new TextRun({ text: 'Generated by Lumenci AI', italics: true })],
                        alignment: AlignmentType.RIGHT,
                    }),
                ],
            }],
        });

        const buffer = await Packer.toBuffer(doc);
        const safeTitle = title.replace(/\.[^/.]+$/, '').replace(/[^a-zA-Z0-9_\- ]/g, '_');

        return {
            statusCode: 200,
            headers: {
                ...CORS_HEADERS,
                'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'Content-Disposition': `attachment; filename="${safeTitle}.docx"`,
            },
            body: buffer.toString('base64'),
            isBase64Encoded: true,
        };
    } catch (error) {
        console.error('Export error:', error);
        return {
            statusCode: 500,
            headers: CORS_HEADERS,
            body: JSON.stringify({ message: 'Error exporting document' }),
        };
    }
};
