import { Document, Packer, Paragraph, Table, TableCell, TableRow, WidthType, AlignmentType, HeadingLevel, TextRun } from 'docx';

export async function generateDocx(title: string, elements: any[]) {
    const headerCell = (text: string, width: number) =>
        new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })],
            width: { size: width, type: WidthType.PERCENTAGE }
        });

    const bodyCell = (text: string) =>
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: text || '' })] })] });

    const doc = new Document({
        sections: [
            {
                properties: {},
                children: [
                    new Paragraph({
                        children: [new TextRun({ text: `Claim Chart: ${title}`, bold: true })],
                        heading: HeadingLevel.HEADING_1,
                        alignment: AlignmentType.CENTER,
                    }),
                    new Paragraph({ children: [] }), // Spacer
                    new Table({
                        width: { size: 100, type: WidthType.PERCENTAGE },
                        rows: [
                            new TableRow({
                                children: [
                                    headerCell('ID', 10),
                                    headerCell('Claim Element', 30),
                                    headerCell('Evidence', 30),
                                    headerCell('Reasoning', 30),
                                ],
                            }),
                            ...elements.map(el => new TableRow({
                                children: [
                                    bodyCell(el.id),
                                    bodyCell(el.element),
                                    bodyCell(el.evidence),
                                    bodyCell(el.reasoning),
                                ],
                            })),
                        ],
                    }),
                    new Paragraph({ children: [] }),
                    new Paragraph({
                        children: [new TextRun({ text: 'Generated by Lumenci AI', italics: true })],
                        alignment: AlignmentType.RIGHT,
                    }),
                ],
            },
        ],
    });

    return await Packer.toBuffer(doc);
}
